// <auto-generated />
using System;
using Leiturinha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leiturinha.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102222342_AtualizarModeloAvaliacao")]
    partial class AtualizarModeloAvaliacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leiturinha.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataAvaliacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<double>("Nota")
                        .HasColumnType("float");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("Leiturinha.Models.ClassificacaoIndicativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FaixaEtaria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Classificacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FaixaEtaria = "0–2 anos"
                        },
                        new
                        {
                            Id = 2,
                            FaixaEtaria = "3–5 anos"
                        },
                        new
                        {
                            Id = 3,
                            FaixaEtaria = "6–7 anos"
                        },
                        new
                        {
                            Id = 4,
                            FaixaEtaria = "8–9 anos"
                        },
                        new
                        {
                            Id = 5,
                            FaixaEtaria = "10–12 anos"
                        });
                });

            modelBuilder.Entity("Leiturinha.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataComentario")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<string>("TextoComentario")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Leiturinha.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Aventura"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Contos"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Fábulas"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Fantasia"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Poesia infantil"
                        });
                });

            modelBuilder.Entity("Leiturinha.Models.ImagemLivro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DescricaoFoto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("ImagemLivro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaminhoImagem = "~/img/1/o-menino-maluquinho2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 1
                        },
                        new
                        {
                            Id = 2,
                            CaminhoImagem = "~/img/2/maluquinho-de-familia2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 2
                        },
                        new
                        {
                            Id = 3,
                            CaminhoImagem = "~/img/3/como-ser-amigo2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 3
                        },
                        new
                        {
                            Id = 4,
                            CaminhoImagem = "~/img/6/a-ursinha-que-nao-dormia-sozinha2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 6
                        },
                        new
                        {
                            Id = 5,
                            CaminhoImagem = "~/img/6/a-ursinha-que-nao-dormia-sozinha3.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 6
                        },
                        new
                        {
                            Id = 6,
                            CaminhoImagem = "~/img/7/coraline2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 7
                        },
                        new
                        {
                            Id = 7,
                            CaminhoImagem = "~/img/7/coraline3.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 7
                        },
                        new
                        {
                            Id = 8,
                            CaminhoImagem = "~/img/8/as-aventuras-de-nino2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 8
                        },
                        new
                        {
                            Id = 9,
                            CaminhoImagem = "~/img/9/menina-bonita-do-laco-de-fita2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 9
                        },
                        new
                        {
                            Id = 10,
                            CaminhoImagem = "~/img/9/menina-bonita-do-laco-de-fita3.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 9
                        },
                        new
                        {
                            Id = 11,
                            CaminhoImagem = "~/img/9/menina-bonita-do-laco-de-fita4.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 9
                        },
                        new
                        {
                            Id = 12,
                            CaminhoImagem = "~/img/12/o-pedido-da-fada-madrinha2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 11
                        },
                        new
                        {
                            Id = 13,
                            CaminhoImagem = "~/img/12/o-pedido-da-fada-madrinha3.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 11
                        },
                        new
                        {
                            Id = 14,
                            CaminhoImagem = "~/img/12/o-pedido-da-fada-madrinha4.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 11
                        },
                        new
                        {
                            Id = 15,
                            CaminhoImagem = "~/img/30/simao-e-o-osso3.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 23
                        },
                        new
                        {
                            Id = 16,
                            CaminhoImagem = "~/img/34/chorar-e-como-chover2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 26
                        },
                        new
                        {
                            Id = 17,
                            CaminhoImagem = "~/img/34/chorar-e-como-chover3.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 26
                        },
                        new
                        {
                            Id = 18,
                            CaminhoImagem = "~/img/34/chorar-e-como-chover4.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 26
                        },
                        new
                        {
                            Id = 19,
                            CaminhoImagem = "~/img/40/alice-no-pais-das-maravilhas2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 27
                        },
                        new
                        {
                            Id = 20,
                            CaminhoImagem = "~/img/40/alice-no-pais-das-maravilhas3.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 27
                        },
                        new
                        {
                            Id = 21,
                            CaminhoImagem = "~/img/40/alice-no-pais-das-maravilhas4.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 27
                        },
                        new
                        {
                            Id = 22,
                            CaminhoImagem = "~/img/47/versos-magicos2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 28
                        });
                });

            modelBuilder.Entity("Leiturinha.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Capa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassificacaoIndicativaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("bit");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("ClassificacaoIndicativaId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Ziraldo",
                            Capa = "~/img/1/o-menino-maluquinho1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "O Menino Maluquinho é um garoto alegre, criativo e cheio de energia. Com suas travessuras, brincadeiras e versinhos, ele espalha diversão por onde passa e mostra que a verdadeira felicidade está na amizade e no amor.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "O Menino Maluquinho"
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Ziraldo",
                            Capa = "~/img/2/maluquinho-de-familia1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Ao investigar suas origens para um trabalho escolar sobre a família real do Brasil, o Menino Maluquinho percebe que não sabe nada sobre sua genealogia. Com a ajuda do álbum de fotos antigas do avô, ele embarca numa divertida jornada pelas memórias da família e descobre que a maluquice é uma herança de sangue.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "Maluquinho de família"
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Molly Wigand",
                            Capa = "~/img/3/como-ser-amigo1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Neste livro, Molly Wigand ensina às crianças os pilares de uma boa amizade — lealdade, verdade e honestidade — e mostra, de forma acessível e carinhosa, como elas podem cultivar relações saudáveis e se tornar ótimos amigos.",
                            Destaque = true,
                            GeneroId = 5,
                            Titulo = "Como ser Amigo: um Livro Sobre Amizade"
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Ana Maria Machado",
                            Capa = "~/img/4/o-tesouro-da-raposa1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "A simpática Raposa revelou a Mico Maneco que tem um tesouro. Curioso, Maneco faz de tudo para descobrir onde se esconde tanta riqueza.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "O tesouro da raposa"
                        },
                        new
                        {
                            Id = 6,
                            Autor = "Emília Nuñez",
                            Capa = "~/img/6/a-ursinha-que-nao-dormia-sozinha1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "A história acompanha Ursita, uma filhotinha que adora dormir na cama dos pais. Com carinho e apoio da família, ela aprende a ter confiança para dormir sozinha em sua própria caminha, descobrindo que sonhos tranquilos também podem acontecer ali.",
                            Destaque = true,
                            GeneroId = 1,
                            Titulo = "A ursinha que não queria dormir sozinha"
                        },
                        new
                        {
                            Id = 7,
                            Autor = "Neil Gaiman",
                            Capa = "~/img/7/coraline1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Ao se mudar para uma casa antiga com os pais, Coraline descobre uma porta secreta que a leva a um mundo paralelo. Lá, tudo parece perfeito: seus \"outros pais\" são atenciosos e o ambiente é encantador. Mas logo ela percebe que esse universo esconde perigos sombrios, e retornar à sua verdadeira casa será uma jornada assustadora e desafiadora.",
                            Destaque = true,
                            GeneroId = 1,
                            Titulo = "Coraline"
                        },
                        new
                        {
                            Id = 8,
                            Autor = "Joana Bragança",
                            Capa = "~/img/8/as-aventuras-de-nino1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Nino Aprende a Esperar, Nino e o Som Misterioso e Nino e o Tesouro Esquecido são três histórias ilustradas e encantadoras que acompanham o esquilo Nino enquanto descobre valores importantes como a paciência, a coragem e a honestidade.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "As Aventuras do Nino"
                        },
                        new
                        {
                            Id = 9,
                            Autor = "Ana Maria Machado",
                            Capa = "~/img/9/menina-bonita-do-laco-de-fita1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Uma linda menina negra desperta a admiração de um coelho branco, que deseja ter uma filha tão pretinha quanto ela. Cada vez que ele lhe pergunta qual o segredo de sua cor, ela inventa uma história.",
                            Destaque = true,
                            GeneroId = 1,
                            Titulo = "Menina bonita do laço de fita"
                        },
                        new
                        {
                            Id = 10,
                            Autor = "Ziraldo",
                            Capa = "~/img/10/meu-amigo-canguru1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Ziraldo relembra sua infância. Na enciclopédia, entre o A e o F, ele encontrou a figura de um canguru. Foi amor à primeira vista.",
                            Destaque = true,
                            GeneroId = 1,
                            Titulo = "Meu Amigo, o Canguru"
                        },
                        new
                        {
                            Id = 11,
                            Autor = "Janaina Tokitaka",
                            Capa = "~/img/12/o-pedido-da-fada-madrinha1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "A Fada Madrinha está cansada! Hoje é o aniversário dela e ela resolve tirar um dia de folga. O que acontecerá com o reino encantado?",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "O pedido da Fada Madrinha"
                        },
                        new
                        {
                            Id = 12,
                            Autor = "Ana Maria Machado",
                            Capa = "~/img/14/camilao-o-comilao1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Conheça o Camilo, um simpático leitão, amigo de todo mundo, mas um grande comilão!",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "Camilão, o comilão"
                        },
                        new
                        {
                            Id = 13,
                            Autor = "Ruth Rocha",
                            Capa = "~/img/15/a-primaveira-da-lagarta1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Depois de uma reunião debaixo da bananeira da floresta, os bichos decidem caçar a lagarta.",
                            Destaque = true,
                            GeneroId = 3,
                            Titulo = "A primavera da lagarta"
                        },
                        new
                        {
                            Id = 14,
                            Autor = "Antoine de Saint-Exupéry",
                            Capa = "~/img/18/o-pequeno-principe1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Um piloto encontra um pequeno príncipe que o leva a uma aventura filosófica e poética.",
                            Destaque = true,
                            GeneroId = 3,
                            Titulo = "O Pequeno Príncipe"
                        },
                        new
                        {
                            Id = 15,
                            Autor = "Vários Autores",
                            Capa = "~/img/19/o-patinho-feio1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "O patinho feio é rejeitado por sua família e parte em busca de aceitação.",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "O Patinho Feio"
                        },
                        new
                        {
                            Id = 16,
                            Autor = "Christian Hans Andersen",
                            Capa = "~/img/20/o-soldadinho-de-chumbo.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Contos clássicos de Andersen compilados neste volume.",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "O Soldadinho de Chumbo: e Outros Contos de Andersen"
                        },
                        new
                        {
                            Id = 17,
                            Autor = "Avelino Guedes",
                            Capa = "~/img/22/o-sanduiche-da-maricota.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "A galinha Maricota prepara um sanduíche e a bicharada dá palpites.",
                            Destaque = true,
                            GeneroId = 3,
                            Titulo = "O sanduíche da Maricota"
                        },
                        new
                        {
                            Id = 18,
                            Autor = "Tim Warnes",
                            Capa = "~/img/25/perigoso-contem-coelhos1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Uma história hilária sobre amizade e rótulos.",
                            Destaque = true,
                            GeneroId = 3,
                            Titulo = "Perigoso! Este Livro Contém Coelhos!"
                        },
                        new
                        {
                            Id = 19,
                            Autor = "Ruth Rocha",
                            Capa = "~/img/26/rato-do-campo-e-da-cidade.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Uma deliciosa fábula sobre diferenças entre campo e cidade.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "O rato do campo e o rato da cidade"
                        },
                        new
                        {
                            Id = 20,
                            Autor = "Ciranda Cultural",
                            Capa = "~/img/27/a-raposa-e-as-uvas1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Uma história sobre humildade e paciência.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "A raposa e as uvas"
                        },
                        new
                        {
                            Id = 21,
                            Autor = "Tatiana Belinky",
                            Capa = "~/img/28/contos-de-muitos-povos.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Contos populares recontados com leveza e humor.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "Contos de Muitos Povos"
                        },
                        new
                        {
                            Id = 22,
                            Autor = "Pé da Letra",
                            Capa = "~/img/29/lobo-e-os-sete-cabritinhos.jpg",
                            ClassificacaoIndicativaId = 1,
                            Descricao = "Uma cabra deixa seus sete filhos sozinhos em casa e alerta sobre o Lobo Mau.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "O Lobo e os Sete Cabritinhos"
                        },
                        new
                        {
                            Id = 23,
                            Autor = "Corey Tabor",
                            Capa = "~/img/30/simao-e-o-osso1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Uma lição sobre empatia em forma de história infantil.",
                            Destaque = true,
                            GeneroId = 3,
                            Titulo = "Simão e o osso"
                        },
                        new
                        {
                            Id = 24,
                            Autor = "Geizy Reis",
                            Capa = "~/img/31/o-reino-das-cores.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Sete reinos, cada um com uma cor; no fim descobrem o valor da união.",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "O Reino das Cores"
                        },
                        new
                        {
                            Id = 25,
                            Autor = "Elisa De Biase Hopman",
                            Capa = "~/img/32/a-floresta-encantada.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Várias cenas da floresta descritas com leveza e ilustrações primorosas.",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "A Floresta Encantada"
                        },
                        new
                        {
                            Id = 26,
                            Autor = "Emília Nuñez",
                            Capa = "~/img/34/chorar-e-como-chover1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Uma história para refletir sobre emoções da infância.",
                            Destaque = true,
                            GeneroId = 4,
                            Titulo = "Chorar é como Chover"
                        },
                        new
                        {
                            Id = 27,
                            Autor = "Lewis Carroll",
                            Capa = "~/img/40/alice-no-pais-das-maravilhas1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Alice segue o Coelho Branco até uma toca e vive aventuras maravilhosas.",
                            Destaque = true,
                            GeneroId = 4,
                            Titulo = "Alice no País das Maravilhas"
                        },
                        new
                        {
                            Id = 28,
                            Autor = "Van Macedo",
                            Capa = "~/img/47/versos-magicos1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Poemas que inspiram a criatividade dos pequenos leitores.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Versos Mágicos"
                        },
                        new
                        {
                            Id = 29,
                            Autor = "José Paulo Paes",
                            Capa = "~/img/48/poemas-para-brincar1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Um clássico da poesia infantil brasileira para brincar com a língua.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Poemas para Brincar"
                        },
                        new
                        {
                            Id = 30,
                            Autor = "Eduardo Rodrigues",
                            Capa = "~/img/49/pequenos-poemas.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Pequenos poemas que convidam à graça das coisas cotidianas.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Pequenos Poemas Para Pequenos"
                        },
                        new
                        {
                            Id = 31,
                            Autor = "Roseana Murray e Roger Mello",
                            Capa = "~/img/50/jardins1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Quinze pequenos poemas que representam jardins variados.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Jardins"
                        });
                });

            modelBuilder.Entity("Leiturinha.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1f1a6c2-1111-4b1e-bf6e-2a9f5f4a9f01",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe82f5d5-fae9-40e8-b93f-2be5d2415119",
                            DataNascimento = new DateTime(2006, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "taynasuperti@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/no-photo.png",
                            LockoutEnabled = true,
                            Nome = "Tayná Carolina Miguel Superti",
                            NormalizedEmail = "TAYNASUPERTI@GMAIL.COM",
                            NormalizedUserName = "TAYNASUPERTI",
                            PasswordHash = "AQAAAAIAAYagAAAAEAnn5BbwkonPozqX+AGFSrcwOhHka/DDKsU7x1LYWumpvBidSQryP/pE7HeBxT75qg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "05bfcf8f-452d-48d2-b66d-131692fb9a74",
                            TwoFactorEnabled = false,
                            UserName = "taynasuperti"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "bec71b05-8f3d-4849-88bb-0e8d518d2de8",
                            Name = "Funcionário",
                            NormalizedName = "FUNCIONÁRIO"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("PerfilRegra", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioRegra", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioPerfil", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a1f1a6c2-1111-4b1e-bf6e-2a9f5f4a9f01",
                            RoleId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        },
                        new
                        {
                            UserId = "a1f1a6c2-1111-4b1e-bf6e-2a9f5f4a9f01",
                            RoleId = "bec71b05-8f3d-4849-88bb-0e8d518d2de8"
                        },
                        new
                        {
                            UserId = "a1f1a6c2-1111-4b1e-bf6e-2a9f5f4a9f01",
                            RoleId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsuarioToken", (string)null);
                });

            modelBuilder.Entity("Leiturinha.Models.Avaliacao", b =>
                {
                    b.HasOne("Leiturinha.Models.Livro", "Livro")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leiturinha.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Leiturinha.Models.Comentario", b =>
                {
                    b.HasOne("Leiturinha.Models.Livro", "Livro")
                        .WithMany("Comentarios")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leiturinha.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Leiturinha.Models.ImagemLivro", b =>
                {
                    b.HasOne("Leiturinha.Models.Livro", "Livro")
                        .WithMany("Imagens")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Leiturinha.Models.Livro", b =>
                {
                    b.HasOne("Leiturinha.Models.ClassificacaoIndicativa", "ClassificacaoIndicativa")
                        .WithMany("Livros")
                        .HasForeignKey("ClassificacaoIndicativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leiturinha.Models.Genero", "Genero")
                        .WithMany("Livros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassificacaoIndicativa");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Leiturinha.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Leiturinha.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leiturinha.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Leiturinha.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Leiturinha.Models.ClassificacaoIndicativa", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("Leiturinha.Models.Genero", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("Leiturinha.Models.Livro", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Comentarios");

                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
