// <auto-generated />
using System;
using Leiturinha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leiturinha.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leiturinha.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataAvaliacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("Leiturinha.Models.ClassificacaoIndicativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FaixaEtaria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Classificacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FaixaEtaria = "0–2 anos"
                        },
                        new
                        {
                            Id = 2,
                            FaixaEtaria = "3–5 anos"
                        },
                        new
                        {
                            Id = 3,
                            FaixaEtaria = "6–7 anos"
                        },
                        new
                        {
                            Id = 4,
                            FaixaEtaria = "8–9 anos"
                        },
                        new
                        {
                            Id = 5,
                            FaixaEtaria = "10–12 anos"
                        });
                });

            modelBuilder.Entity("Leiturinha.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<DateTimeOffset>("DataComentario")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Leiturinha.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Aventura"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Contos"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Fábulas"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Fantasia"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Poesia infantil"
                        });
                });

            modelBuilder.Entity("Leiturinha.Models.ImagemLivro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DescricaoFoto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("ImagemLivro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaminhoImagem = "~/img/1/o-menino-maluquinho2.jpg",
                            DescricaoFoto = "Foto adicional",
                            LivroId = 1
                        },
                        new
                        {
                            Id = 2,
                            CaminhoImagem = "~/img/2/maluquinho-de-familia2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 2
                        },
                        new
                        {
                            Id = 3,
                            CaminhoImagem = "~/img/3/como-ser-amigo2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 3
                        },
                        new
                        {
                            Id = 4,
                            CaminhoImagem = "~/img/4/o-tesouro-da-raposa2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 4
                        },
                        new
                        {
                            Id = 5,
                            CaminhoImagem = "~/img/5/a-cesta-da-dona-maricota2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 5
                        },
                        new
                        {
                            Id = 6,
                            CaminhoImagem = "~/img/5/a-cesta-da-dona-maricota3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 5
                        },
                        new
                        {
                            Id = 7,
                            CaminhoImagem = "~/img/6/a-ursinha-que-nao-dormia-sozinha2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 6
                        },
                        new
                        {
                            Id = 8,
                            CaminhoImagem = "~/img/6/a-ursinha-que-nao-dormia-sozinha3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 6
                        },
                        new
                        {
                            Id = 9,
                            CaminhoImagem = "~/img/7/o-reizinho-mandao2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 7
                        },
                        new
                        {
                            Id = 10,
                            CaminhoImagem = "~/img/8/as-aventuras-de-nino2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 8
                        },
                        new
                        {
                            Id = 11,
                            CaminhoImagem = "~/img/9/menina-bonita-do-laco-de-fita2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 9
                        },
                        new
                        {
                            Id = 12,
                            CaminhoImagem = "~/img/9/menina-bonita-do-laco-de-fita3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 9
                        },
                        new
                        {
                            Id = 13,
                            CaminhoImagem = "~/img/9/menina-bonita-do-laco-de-fita4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 9
                        },
                        new
                        {
                            Id = 14,
                            CaminhoImagem = "~/img/12/o-pedido-da-fada-madrinha2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 12
                        },
                        new
                        {
                            Id = 15,
                            CaminhoImagem = "~/img/12/o-pedido-da-fada-madrinha3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 12
                        },
                        new
                        {
                            Id = 16,
                            CaminhoImagem = "~/img/12/o-pedido-da-fada-madrinha4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 12
                        },
                        new
                        {
                            Id = 17,
                            CaminhoImagem = "~/img/13/chapeuzinho-vermelho2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 13
                        },
                        new
                        {
                            Id = 18,
                            CaminhoImagem = "~/img/13/chapeuzinho-vermelho3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 13
                        },
                        new
                        {
                            Id = 19,
                            CaminhoImagem = "~/img/15/a-primaveira-da-lagarta2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 15
                        },
                        new
                        {
                            Id = 20,
                            CaminhoImagem = "~/img/16/joao-e-o-pe-de-feijao2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 16
                        },
                        new
                        {
                            Id = 21,
                            CaminhoImagem = "~/img/16/joao-e-o-pe-de-feijao3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 16
                        },
                        new
                        {
                            Id = 22,
                            CaminhoImagem = "~/img/16/joao-e-o-pe-de-feijao4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 16
                        },
                        new
                        {
                            Id = 23,
                            CaminhoImagem = "~/img/17/os-tres-porquinhos2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 17
                        },
                        new
                        {
                            Id = 24,
                            CaminhoImagem = "~/img/17/os-tres-porquinhos3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 17
                        },
                        new
                        {
                            Id = 25,
                            CaminhoImagem = "~/img/17/os-tres-porquinhos4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 17
                        },
                        new
                        {
                            Id = 26,
                            CaminhoImagem = "~/img/18/o-pequeno-principe2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 18
                        },
                        new
                        {
                            Id = 27,
                            CaminhoImagem = "~/img/18/o-pequeno-principe3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 18
                        },
                        new
                        {
                            Id = 28,
                            CaminhoImagem = "~/img/19/o-patinho-feio2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 19
                        },
                        new
                        {
                            Id = 29,
                            CaminhoImagem = "~/img/21/a-cigarra-e-a-formiga2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 21
                        },
                        new
                        {
                            Id = 30,
                            CaminhoImagem = "~/img/23/a-lebre-e-a-tartaruga2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 23
                        },
                        new
                        {
                            Id = 31,
                            CaminhoImagem = "~/img/23/a-lebre-e-a-tartaruga3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 23
                        },
                        new
                        {
                            Id = 32,
                            CaminhoImagem = "~/img/24/fabulas-de-escopo2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 24
                        },
                        new
                        {
                            Id = 33,
                            CaminhoImagem = "~/img/25/perigoso-contem-coelhos2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 25
                        },
                        new
                        {
                            Id = 34,
                            CaminhoImagem = "~/img/25/perigoso-contem-coelhos3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 25
                        },
                        new
                        {
                            Id = 35,
                            CaminhoImagem = "~/img/27/a-raposa-e-as-uvas2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 27
                        },
                        new
                        {
                            Id = 36,
                            CaminhoImagem = "~/img/30/simao-e-o-osso2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 30
                        },
                        new
                        {
                            Id = 37,
                            CaminhoImagem = "~/img/30/simao-e-o-osso3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 30
                        },
                        new
                        {
                            Id = 38,
                            CaminhoImagem = "~/img/33/dragoes-de-terrazul2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 33
                        },
                        new
                        {
                            Id = 39,
                            CaminhoImagem = "~/img/33/dragoes-de-terrazul3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 33
                        },
                        new
                        {
                            Id = 40,
                            CaminhoImagem = "~/img/33/dragoes-de-terrazul4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 33
                        },
                        new
                        {
                            Id = 41,
                            CaminhoImagem = "~/img/34/chorar-e-como-chover2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 34
                        },
                        new
                        {
                            Id = 42,
                            CaminhoImagem = "~/img/34/chorar-e-como-chover3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 34
                        },
                        new
                        {
                            Id = 43,
                            CaminhoImagem = "~/img/34/chorar-e-como-chover4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 34
                        },
                        new
                        {
                            Id = 44,
                            CaminhoImagem = "~/img/35/maluquinho-de-familia2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 35
                        },
                        new
                        {
                            Id = 45,
                            CaminhoImagem = "~/img/35/maluquinho-de-familia3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 35
                        },
                        new
                        {
                            Id = 46,
                            CaminhoImagem = "~/img/35/maluquinho-de-familia4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 35
                        },
                        new
                        {
                            Id = 47,
                            CaminhoImagem = "~/img/37/zumbi-net2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 37
                        },
                        new
                        {
                            Id = 48,
                            CaminhoImagem = "~/img/37/zumbi-net3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 37
                        },
                        new
                        {
                            Id = 49,
                            CaminhoImagem = "~/img/38/gildo2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 38
                        },
                        new
                        {
                            Id = 50,
                            CaminhoImagem = "~/img/39/o-reino-do-tempo2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 39
                        },
                        new
                        {
                            Id = 51,
                            CaminhoImagem = "~/img/40/alice-no-pais-das-maravilhas2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 40
                        },
                        new
                        {
                            Id = 52,
                            CaminhoImagem = "~/img/40/alice-no-pais-das-maravilhas3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 40
                        },
                        new
                        {
                            Id = 53,
                            CaminhoImagem = "~/img/40/alice-no-pais-das-maravilhas4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 40
                        },
                        new
                        {
                            Id = 54,
                            CaminhoImagem = "~/img/41/a-arca-de-noe2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 41
                        },
                        new
                        {
                            Id = 55,
                            CaminhoImagem = "~/img/42/som-do-rugido-da-onca2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 42
                        },
                        new
                        {
                            Id = 56,
                            CaminhoImagem = "~/img/42/som-do-rugido-da-onca3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 42
                        },
                        new
                        {
                            Id = 57,
                            CaminhoImagem = "~/img/42/som-do-rugido-da-onca4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 42
                        },
                        new
                        {
                            Id = 58,
                            CaminhoImagem = "~/img/43/cantigas-de-roda3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 43
                        },
                        new
                        {
                            Id = 59,
                            CaminhoImagem = "~/img/44/mas-que-festa2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 44
                        },
                        new
                        {
                            Id = 60,
                            CaminhoImagem = "~/img/44/mas-que-festa3.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 44
                        },
                        new
                        {
                            Id = 61,
                            CaminhoImagem = "~/img/44/mas-que-festa4.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 44
                        },
                        new
                        {
                            Id = 62,
                            CaminhoImagem = "~/img/45/o-caso-dos-ovos2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 45
                        },
                        new
                        {
                            Id = 63,
                            CaminhoImagem = "~/img/46/catigamente2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 46
                        },
                        new
                        {
                            Id = 64,
                            CaminhoImagem = "~/img/47/versos-magicos2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 47
                        },
                        new
                        {
                            Id = 65,
                            CaminhoImagem = "~/img/48/poemas-para-brincar2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 48
                        },
                        new
                        {
                            Id = 66,
                            CaminhoImagem = "~/img/50/jardins2.jpg",
                            DescricaoFoto = "Contra capa",
                            LivroId = 50
                        });
                });

            modelBuilder.Entity("Leiturinha.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Capa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassificacaoIndicativaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("bit");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("ClassificacaoIndicativaId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Ziraldo",
                            Capa = "~/img/1/o-menino-maluquinho1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Um garoto cheio de energia e criatividade, o Menino Maluquinho vive aprontando travessuras, inventando brincadeiras e alegrando todos ao redor. Entre versinhos, canções e confusões, ele mostra que ser feliz é estar cercado de amigos e amor.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "O Menino Maluquinho"
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Ziraldo",
                            Capa = "~/img/2/maluquinho-de-familia1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Tudo começa com um trabalho escolar: a professora pede uma pesquisa sobre a família real do Brasil. A turma se diverte revelando suas origens, mas o Menino Maluquinho não sabe nada sobre sua árvore genealógica. A partir daí, ele embarca numa aventura com o álbum de fotos antigas do avô, descobrindo memórias familiares e percebendo que a maluquice está em seu DNA.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "Maluquinho de família"
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Molly Wigand",
                            Capa = "~/img/3/como-ser-amigo1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Em Como ser amigo - Um livro sobre amizade... Feito pra mim!, a autora Molly Wigand apresenta às crianças os valores que ajudam a construir boas amizades: lealdade, verdade e honestidade. E como as crianças podem se tornar boas amigas umas das outras.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Como ser Amigo: um Livro Sobre Amizade"
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Ana Maria Machado",
                            Capa = "~/img/4/o-tesouro-da-raposa1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "A simpática Raposa revelou a Mico Maneco que tem um tesouro. Curioso, Maneco faz de tudo para descobrir onde se esconde tanta riqueza.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "O tesouro da raposa"
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Tatiana Belinky",
                            Capa = "~/img/5/a-cesta-da-dona-maricota1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Em deliciosos versos e rimas, os alimentos que compõem a cesta de Dona Maricota chegam da feira e iniciam uma gostosa provocação, enumerando as vantagens nutritivas de se comer, verduras, frutas e legumes.Indicado para os anos iniciais do Ensino Fundamental 1º ano e 2º ano, com trabalho interdisciplinar: Ciências da Natureza.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "A cesta de dona Maricota"
                        },
                        new
                        {
                            Id = 6,
                            Autor = "Emília Nuñez",
                            Capa = "~/img/6/a-ursinha-que-nao-dormia-sozinha1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Dormir na cama dos pais é uma delícia! Mas os pequenos crescem e chega o momento de dormir na sua própria caminha. Nesta história, Ursita e sua família encontram juntos a confiança para que a filhotinha durma sozinha e tenha sonhos tranquilos!",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "A ursinha que não queria dormir sozinha"
                        },
                        new
                        {
                            Id = 7,
                            Autor = "Neil Gaiman",
                            Capa = "~/img/7/o-reizinho-mandao1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Certas portas não devem ser abertas. E Coraline descobre isso pouco tempo depois de chegar com os pais à sua nova casa, um apartamento em um casarão antigo ocupado por vizinhos excêntricos e envolto por uma névoa insistente, um mundo de estranhezas e magia, o tipo de universo que apenas Neil Gaiman pode criar.\r\n\r\nAo abrir uma porta misteriosa na sala de casa, a menina se depara com um lugar macabro e fascinante. Ali, naquele outro mundo, seus outros pais são criaturas muito pálidas, com botões negros no lugar dos olhos, sempre dispostos a lhe dar atenção, fazer suas comidas preferidas e mostrar os brinquedos mais divertidos. Coraline enfim se sente... em casa. Mas essa sensação logo desaparece, quando ela descobre que o lugar guarda mistérios e perigos, e a menina se dá conta de que voltar para sua verdadeira casa vai ser muito mais difícil ― e assustador ― do que imaginava.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "Coraline"
                        },
                        new
                        {
                            Id = 8,
                            Autor = "Joana Bragança ",
                            Capa = "~/img/8/as-aventuras-de-nino1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Nino Aprende a Esperar, Nino e o Som Misterioso e Nino e o Tesouro Esquecido são três histórias ilustradas e encantadoras que acompanham o esquilo Nino enquanto descobre valores importantes como a paciência, a coragem e a honestidade.\r\nIdeal para crianças dos 3 aos 7 anos, este livro incentiva o diálogo sobre emoções e atitudes positivas, num universo mágico, colorido e cheio de ternura.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "As Aventuras do Nino - Volume 1: Nino Aprende a Esperar & Nino e o Som Misterioso & Nino e o Tesouro Esquecido"
                        },
                        new
                        {
                            Id = 9,
                            Autor = "Ana Maria Machado",
                            Capa = "~/img/9/menina-bonita-do-laco-de-fita1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Uma linda menina negra desperta a admiração de um coelho branco, que deseja ter uma filha tão pretinha quanto ela. Cada vez que ele lhe pergunta qual o segredo de sua cor, ela inventa uma história. O coelho segue todos os “conselhos” da menina, mas continua branco. Esta narrativa delicada e tocante aborda temas como autoaceitação, respeito às diferenças e a beleza da diversidade. Com ilustrações encantadoras e uma mensagem poderosa, o livro convida os leitores a refletir sobre a importância de valorizar a singularidade de cada pessoa, independentemente de sua cor de pele.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "Menina bonita do laço de fita"
                        },
                        new
                        {
                            Id = 10,
                            Autor = "Ziraldo",
                            Capa = "~/img/10/meu-amigo-canguru1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Ziraldo relembra sua infância. Na enciclopédia, entre o A e o F, ele encontrou a figura de um canguru. Foi amor à primeira vista. Gugu foi seu amigo de infância, de sonhos e fantasias, de ternura e aconchego. Ziraldo cresceu, tornou-se escritor, desenhista, artista, e o canguru, sempre à vista.",
                            Destaque = false,
                            GeneroId = 1,
                            Titulo = "Meu Amigo, o Canguru"
                        },
                        new
                        {
                            Id = 11,
                            Autor = "Ana Maria Machado",
                            Capa = "~/img/11/branca-de-neve.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Os mais clássicos contos de fadas em formato diferente para as crianças se divertirem com a historinha ao mesmo tempo que brincam com um quebracabeça à cada página.",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "Branca de Neve e os Sete Anões | Livro Quebra-Cabeça"
                        },
                        new
                        {
                            Id = 12,
                            Autor = "Janaina Tokitaka",
                            Capa = "~/img/12/o-pedido-da-fada-madrinha1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "A Fada Madrinha está cansada! Afinal, ela trabalha sem parar para atender a todos os pedidos das princesas dos contos de fadas. Mas hoje é uma data especial: é o aniversário da Fada Madrinha! E se ela resolvesse tirar um merecido dia de folga? O que será que aconteceria com o reino encantado?\r\nEsta nova versão da Fada Madrinha apresentada nesta história da coleção Canoa vai mudar a relação que temos com a já tão conhecida personagem de tantos contos de fadas. Escrito por Janaina Tokitaka e ricamente ilustrado por Flávia Borges, este livro vai surpreender, fazer pensar e arrancar risadas de crianças e adultos. A coleção Canoa tem como objetivo levar literatura infantil de qualidade a um preço popular para todos os pequenos leitores.",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "O pedido da Fada Madrinha"
                        },
                        new
                        {
                            Id = 13,
                            Autor = "Susie Brooks",
                            Capa = "~/img/13/chapeuzinho-vermelho1.jpg",
                            ClassificacaoIndicativaId = 1,
                            Descricao = "Muito contente, CHAPEUZINHO VERMELHO foi vistar a vovozinha, mas não imaginava que o LOBO MAU estava no lugar da velhinha!",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "Chapeuzinho Vermelho"
                        },
                        new
                        {
                            Id = 14,
                            Autor = "Ana Maria Machado",
                            Capa = "~/img/14/camilao-o-comilao1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Conheça o Camilo, um simpático leitão, amigo de todo mundo, mas um grande comilão! Gosta de comer bem, mas nem tanto de trabalhar. Por isso tudo o que come, ele prefere ganhar. Preguiçoso, sem dúvida, mas tem um bom coração. É impossível não amar nosso amigo Camilão!",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "Camilão, o comilão"
                        },
                        new
                        {
                            Id = 15,
                            Autor = "Ruth Rocha",
                            Capa = "~/img/15/a-primaveira-da-lagarta1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Depois de uma reunião debaixo da bananeira da floresta, a formiga, o louva-a-deus, o camaleão (que vivia mudando de opinião), a joaninha, a lagartixa, a libélula, o gafanhoto, o caracol, a aranha e a cigarra (ufa, quanta gente!, ou melhor, quanto bicho!), decidiram caçar a lagarta, porque ela comia folhas demais (como se eles não comessem nada...). Além disso, eles achavam a lagarta muito feia (como se eles fossem muito lindos...). Porém, a caçada aconteceu no início da primavera, quando as lagartas se transformam em... Bem, é melhor não contar o final da história, que ficou ainda mais bonita com os desenhos da Madalena Elek.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "A primavera da lagarta"
                        },
                        new
                        {
                            Id = 16,
                            Autor = "Igor Barbosa ",
                            Capa = "~/img/16/joao-e-o-pe-de-feijao1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "João mora com sua mãe numa cidade chamada Vila Feliz. Mas como são tempos difíceis, o menino decide trocar a vaca leiteira da família por cinco feijões mágicos que um senhor misterioso ofereceu. Mal sabia ele que aquelas sementes o levariam a uma grande aventura, com o poder de transformar sua vida e o futuro de toda a cidade.",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "João e o Pé de Feijão"
                        },
                        new
                        {
                            Id = 17,
                            Autor = "Tulip Books",
                            Capa = "~/img/17/os-tres-porquinhos1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Dê vida à magia dos contos de fadas para os seus filhos. As histórias atemporais e ilustrações encantadoras nestes livros pop-up logo se tornarão a diversão favorita de todos na hora de dormir e ajudarão seus filhos a cair em um sono mágico e tranquilo.  ",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "Os Três Porquinhos"
                        },
                        new
                        {
                            Id = 18,
                            Autor = "Antoine de Saint-Exupéry",
                            Capa = "~/img/18/o-pequeno-principe1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Nesta história que marcou gerações de leitores em todo o mundo, um piloto cai com seu avião no deserto do Saara e encontra um pequeno príncipe, que o leva a uma aventura filosófica e poética através de planetas que encerram a solidão humana.\r\n\r\nUm livro para todos os públicos, O pequeno príncipe é uma obra atemporal, com metáforas pertinentes e aprendizados sobre afeto, sonhos, esperança e tudo aquilo que é invisível aos olhos. ",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "O Pequeno Príncipe"
                        },
                        new
                        {
                            Id = 19,
                            Autor = " Vários Autores",
                            Capa = "~/img/19/o-patinho-feio1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "O patinho feio é rejeitado por sua família e decide procurar alguém que o aceite como ele é. Leia esta encantadora história e cole os adesivos para completar as cenas.",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "O Patinho Feio"
                        },
                        new
                        {
                            Id = 20,
                            Autor = "Christian Hans Andersen ",
                            Capa = "~/img/20/o-soldadinho-de-chumbo.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "O Soldadinho de Chumbo A Menina dos Fósforos O Pequeno Tuque As Flores de Idinha A Camponesa e o Limpador de Chaminés As Cegonhas João Grande e João Pequeno O Pinheirinho O Rouxinol.",
                            Destaque = false,
                            GeneroId = 2,
                            Titulo = "O Soldadinho de Chumbo: e Outros Contos de Andersen"
                        },
                        new
                        {
                            Id = 21,
                            Autor = " Ciranda Cultural",
                            Capa = "~/img/21/a-cigarra-e-a-formiga1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "A cigarra passava os dias cantando, despreocupadamente, enquanto a formiga trabalhava sem parar. O inverno chegará... quem estará mais preparada para enfrentar essa estação? Acompanhe a história e descubra a importância da solidariedade e da amizade verdadeira.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "A Cigarra e a Formiga"
                        },
                        new
                        {
                            Id = 22,
                            Autor = "Avelino Guedes",
                            Capa = "~/img/22/o-sanduiche-da-maricota.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "A galinha Maricota preparou um sanduíche. Mas, antes de conseguir comer, a bicharada toda começou a chegar e dar palpite para tornar o sanduíche da Maricota mais gostoso (para eles, é claro). O resultado é difícil de explicar. Só mesmo vendo. Vamos ver?",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "O sanduíche da Maricota"
                        },
                        new
                        {
                            Id = 23,
                            Autor = " Ruth Rocha",
                            Capa = "~/img/23/a-lebre-e-a-tartaruga1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Nesta releitura encantadora, a consagrada Ruth Rocha transforma a clássica fábula sobre a corrida entre a lebre e a tartaruga em uma experiência literária única, em que cada verso e cada rima convidam os leitores a refletirem sobre os valores da perseverança e da humildade.  A lebre e a tartaruga é o quarto livro da coleção Recontos Bonitinhos. Nesta série, Ruth Rocha empresta seu olhar e talento únicos para criar poemas e apresentar histórias clássicas para as novas gerações de pequenos leitores.  Na narrativa, que se inicia com um gostoso convite a adentrar o mundo de imaginação - \"Era uma vez uma lebre, que se achava a tal! Um dia, ela desafiou a tranquila tartaruga para uma corrida sensacional. Quem será que chegou primeiro, afinal?\" - a autora usa a cadência dos versos para dar voz a personagens que, apesar de suas diferenças, ensinam que a jornada da vida pode ser recontada de diversas formas. Abordagem que estimula a criatividade e a sensibilidade, transformando a simples corrida em uma metáfora para os desafios e triunfos cotidianos.  Complementando a narrativa, as ilustrações vibrantes e coloridas de Caco Galhardo dão vida aos personagens e cenários, reforçando o caráter lúdico e inspirador da obra. Cada traço e cor colaboram para que o imaginário infantil se expanda, proporcionando uma experiência visual que dialoga perfeitamente com o texto poético.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "A Lebre e a Tartaruga"
                        },
                        new
                        {
                            Id = 24,
                            Autor = "Ruth Rocha",
                            Capa = "~/img/24/fabulas-de-escopo1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Se de fato existiu (há quem duvide), Esopo foi um grego do século VI a.C. Como se lê num texto ao final deste livrinho, suas fábulas “são pequenas histórias de caráter moral e alegórico, nas quais os principais personagens são representados por animais que pensam e falam como humanos. Ao fazer isso, Esopo queria mostrar como o ser humano pode agir em determinadas situações”.Essas pequenas histórias foram transmitidas ao longo dos séculos, num boca a boca que durou aproximadamente dois mil anos, até que autores como o francês Jean de La Fontaine, que viveu no século XVII, decidiram colocá-las no papel. Agora é a vez da Ruth Rocha, que escolheu algumas das mais interessantes, como “A raposa e as uvas”, “A cigarra e a formiga” e “A rã e o touro”, e a elas emprestou sua voz única, graciosa, especial.\r\n",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "Fábulas de Esopo"
                        },
                        new
                        {
                            Id = 25,
                            Autor = "Tim Warnes",
                            Capa = "~/img/25/perigoso-contem-coelhos1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "O melhor amigo do Bob,uma coisa escamosa,encontrou um chapéu.Havia uma etiqueta nele que dizia:PERIGO! NÃO TOQUE! Tire isso! gritou Bob. Pode ser perigoso!Então, de dentro da cartola saltou um coelho.E depois outro! E outro!Mas os coelhos não são perigosos. São?Uma história hilária sobre amizade.E rótulos...",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "Perigoso! Este Livro Contém Coelhos!"
                        },
                        new
                        {
                            Id = 26,
                            Autor = "Ruth Rocha",
                            Capa = "~/img/26/rato-do-campo-e-da-cidade.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Era uma vez uma família de ratos que morava no campo. “Viviam perto de um celeiro, cheinho de grãos, de maneira que sempre tinham o que comer”, nos conta a Ruth Rocha. Um dia eles receberam a visita de um primo da cidade, Jôni Raturbano, que era grã-fino e, sem querer querendo, sempre dava um jeito de criticar a vida rural. Dizia que na cidade é que era bom. Quando chegou a hora de ir embora, Jôni Raturbano convidou seu primo Rateco para ir com ele. Rateco gostou da ideia. Mas será que a cidade grande trataria bem do nosso ratinho?Da série Conta de Novo, O rato do campo e o rato da cidade é uma deliciosa fábula (atribuída a Esopo) sobre as diferenças entre o campo e a cidade, mas também uma defesa sem concessões à dignidade dos homens, ops, quero dizer, dos ratos.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "O rato do campo e o rato da cidade"
                        },
                        new
                        {
                            Id = 27,
                            Autor = "Ciranda Cultural",
                            Capa = "~/img/27/a-raposa-e-as-uvas1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Uma raposa estava andando pela floresta e com vontade de comer algo doce. Ela se deparou com uma parreira cheinha de belas uvas, mas não conseguia pegá-las. Leia esta história que fala sobre humildade e paciência.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "A raposa e as uvas"
                        },
                        new
                        {
                            Id = 28,
                            Autor = "Tatiana Belinky",
                            Capa = "~/img/28/contos-de-muitos-povos.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "As histórias populares são transmitidas de geração em geração e trazem as questões mais humanas, a sabedoria tradicional e as marcas culturais de diferentes povos. É o que se revela nesta obra por meio de contos de diversos lugares do mundo, recontados pela escrita leve, fluida e bem-humorada de Tatiana Belinky.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "Contos de Muitos Povos"
                        },
                        new
                        {
                            Id = 29,
                            Autor = "Pé da Letra",
                            Capa = "~/img/29/lobo-e-os-sete-cabritinhos.jpg",
                            ClassificacaoIndicativaId = 1,
                            Descricao = "Uma cabra deixou seus sete filhos sozinhos em casa enquanto procura comida na floresta. Antes de sair, ela alertou sobre o Lobo Mau, que irá tentar entrar na casa.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "O Lobo e os Sete Cabritinhos"
                        },
                        new
                        {
                            Id = 30,
                            Autor = "Corey Tabor",
                            Capa = "~/img/30/simao-e-o-osso1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Passeando ao redor do lago com seu osso, Simão avista outro cão com um osso melhor e propõe um desafio: quem fizer os truques mais legais, fica com o osso.\r\n\r\nMas ao perceber que o cachorro sabe fazer as mesmas acrobacias que ele, Simão acaba recebendo algo muito melhor do que aquilo que queria: uma lição sobre empatia.\r\n\r\nDo autor vencedor da Medalha Caldecott Corey Tabor, Simão e o osso é uma leitura que vai entreter enquanto ensina sobre generosidade e amizade.",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "Simão e o osso"
                        },
                        new
                        {
                            Id = 31,
                            Autor = " Geizy Reis",
                            Capa = "~/img/31/o-reino-das-cores.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "E se o mundo fosse todo de uma só cor? Teria a mesma graça e esplendor? O reino das cores é uma história que fala exatamente sobre isso. O livro conta a história de sete reinos, cada um com uma única cor. Porém as cores entram numa disputa para mostrar qual era a mais bonita e importante. No fim, elas descobrem que isso não é o principal e que juntas poderiam criar algo encantador. O enredo tem o intuito de abordar o respeito às diferenças, o diálogo, a união. Conta com uma narrativa simples, na qual cores são usadas para representar as pessoas e seus mundos, além de abordar as cores de forma lúdica e atrativa.",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "O Reino das Cores"
                        },
                        new
                        {
                            Id = 32,
                            Autor = "Elisa De Biase Hopman",
                            Capa = "~/img/32/a-floresta-encantada.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Na Floresta Encantada, diferentes animais vivem a sua rotina. A cigarra, o passarinho, o porco-espinho, a formiga, o beija-flor, o macaco, o besouro, o tucano, o pica-pau, a centopeia, as abelhas... e a floresta dá lugar a estas cenas, descritas com leveza pela fonoaudióloga Elisa De Biase Hopman e ilustradas com primor pelo artista Tiago Costa, favorecendo a imaginação e o encanto do pequeno leitor.",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "A Floresta Encantada"
                        },
                        new
                        {
                            Id = 33,
                            Autor = "Ruth Stiles Gannett",
                            Capa = "~/img/33/dragoes-de-terrazul1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Depois de deixar Elmer em Nuncaverde, o bebê dragão parte em direção a Terrazul, o refúgio dos últimos dragões, ansioso pelo reencontro com sua família. Ao sobrevoar o Deserto Terrível, porém, ele percebe, alarmado, que homens descobriram a região e estão capturando dragões para vendê-los ao zoológico. Mais do que nunca, o bebê dragão precisará da ajuda de seu amigo Elmer para resgatar sua família e salvar Terrazul.\r\n\r\nOs dragões de Terrazul é o último livro da trilogia iniciada com O dragão do meu pai e Elmer o dragão. Com uma combinação perfeita de capítulos curtos e ação constante, a história é ideal para crianças que estão ganhando fluência em leitura e que buscam histórias com textos um pouco mais longos, sem abrir mão de uma leitura leve e prazerosa. É também uma escolha certeira para pais que desejam oferecer aos filhos uma aventura inesquecível para ser lida em voz alta ― do tipo que cativa a atenção de tal maneira que é impossível parar antes da última página.",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "Os dragões de Terrazul"
                        },
                        new
                        {
                            Id = 34,
                            Autor = "Emília Nuñez",
                            Capa = "~/img/34/chorar-e-como-chover1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Com ilustrações poéticas e texto emocionante, Chorar é como Chover é uma história para refletir sobre as emoções da infância e a importância de abraçar o que se sente.",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "Chorar é como Chover"
                        },
                        new
                        {
                            Id = 35,
                            Autor = " Chris Saunders e Emília Nuñez",
                            Capa = "~/img/35/acreditar1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "Um livro para sua criança descobrir o que a torna especial! Preguiça vive uma emocionante jornada de autodescoberta enquanto dá o seu melhor para entender o que o faz único. Com a ajuda de seus amigos, ele descobre que a resposta estava dentro dele otempo todo!",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "Acreditar"
                        },
                        new
                        {
                            Id = 36,
                            Autor = "Fiona Watt",
                            Capa = "~/img/36/fadas-do-jardim.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Este livro de adesivos está repleto de fadas para vestir e cenas de um lindo jardim para decorar e vivenciar aventuras divertidas. Com mais de 200 adesivos de roupas, animais e flores para completar as cenas, as crianças vão passar momentos deliciosos decorando o mundo das fadas.",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "A Fada do Jardim"
                        },
                        new
                        {
                            Id = 37,
                            Autor = " Emília Nuñez",
                            Capa = "~/img/37/zumbi-net1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Existe uma lenda urbana que conta de um mundo paralelo no qual as crianças vão parar de tanto exagerar nos games. É o Zumbi.net! Quando Juca encontra Gael congelado na tela do videogame, não tem dúvidas: ele e a sua irmã Cecília vão ter que dar um jeito de entrar no Zumbi.net para resgatar o amigo!",
                            Destaque = false,
                            GeneroId = 3,
                            Titulo = "Zumbi.net"
                        },
                        new
                        {
                            Id = 38,
                            Autor = " Silvana Rando",
                            Capa = "~/img/38/gildo1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Gildo é muito corajoso. Ele gosta de montanha-russa, de avião, de filme de terror e de cantar em público. Mas como quase todo mundo, existe uma coisa que o deixa apavorado... Sempre na noite anterior a alguma festinha de aniversário de um amigo, ele não consegue pregar os olhos, por que será?",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "Gildo"
                        },
                        new
                        {
                            Id = 39,
                            Autor = "Isa Colli",
                            Capa = "~/img/39/o-reino-do-tempo1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Em uma terra distante, os monarcas Solaris e Selíní viviam em harmonia com a natureza, regendo as estações do ano. Com o passar do tempo, porém, eles perceberam que precisavam de ajuda. Quatro crianças mágicas foram, então, preparadas pelo rei e pela rainha para assumir a tarefa de espalhar seus encantos por toda a parte. Desde aqueles dias longínquos, Primavera, Verão, Outono e Inverno, têm a missão de manter o equilíbrio entre si, garantindo a continuidade dessa missão vital para todos os seres do Reino. Cores de pôr-do-sol, cristais brancos e alegrias de fim de tarde aguardam os súditos nessa saga perfumada à natureza.",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "O Reino do Tempo"
                        },
                        new
                        {
                            Id = 40,
                            Autor = "Lewis Carroll",
                            Capa = "~/img/40/alice-no-pais-das-maravilhas1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Uma menina, um coelho e uma história capazes de fazer qualquer um de nós voltar a sonhar. Alice é despertada de um leve sono ao pé de uma árvore por um coelho peculiar. Uma criatura alva e falante com roupas engraçadas, que consulta seu relógio e reclama do próprio atraso. Curiosa como toda criança, Alice segue o animal até cair em um buraco sem fim que mudou para sempre a literatura infantil. Mais de 150 anos depois, Alice no País das Maravilhas continua repleto de ensinamentos para aqueles que ousaram seguir o Coelho Branco até sua toca.",
                            Destaque = false,
                            GeneroId = 4,
                            Titulo = "Alice no País das Maravilhas (Classic Edition)"
                        },
                        new
                        {
                            Id = 41,
                            Autor = "Vinícius de Moraes",
                            Capa = "~/img/41/a-arca-de-noe1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Crianças e adultos sabem de cor alguns dos poemas infantis de Vinicius de Moraes, graças ao ritmo inteligente e bem-humorado dos seus versos. As deliciosas versões musicais de A arca de Noé são exemplo dessa simpatia que o poeta conquistou entre pequenos e grandes leitores. Os discos A arca de Noé 1 (1980) e A arca de Noé 2 (1981) traziam composições como \"O pato\", \"A casa\", \"O gato\", \"O pingüim\" e \"São Francisco\", que se tornaram famosas nas vozes de Chico Buarque, Milton Nascimento, Toquinho, Marina Lima e Ney Matogrosso, entre outros intérpretes. Agora o livro A arca de Noé ganha nova edição, com todos os 32 poemas da edição original, publicada pela Companhia das Letrinhas pela primeira vez em 1993. Ilustrações assinadas por Nelson Cruz compõem a reedição deste clássico infantil. O poeta Vinicius de Moraes (1913-1980) teve um verdadeiro caso de amor com a música brasileira, tornando-se um de seus maiores letristas. A lista de seus parceiros musicais é vasta e inclui Tom Jobim, Baden Powell, Chico Buarque, Carlos Lyra, Edu Lobo e Toquinho, entre outros.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "A Arca de Noé"
                        },
                        new
                        {
                            Id = 42,
                            Autor = " Micheliny Verunschk",
                            Capa = "~/img/42/som-do-rugido-da-onca1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "Em 1817, Spix e Martius desembarcaram no Brasil com a missão de registrar suas impressões sobre o país. Três anos e 10 mil quilômetros depois, os exploradores voltaram a Munique trazendo consigo não apenas um extenso relato da viagem, mas também um menino e uma menina indígenas, que morreriam pouco tempo depois de chegar em solo europeu.\r\nEm seu quinto romance, Micheliny Verunschk constrói uma poderosa narrativa que deixa de lado a historiografia hegemônica para dar protagonismo às crianças ― batizadas aqui de Iñe-e e Juri ― arrancadas de sua terra natal. Entrelaçando a trama do século XIX ao Brasil contemporâneo, somos apresentados também a Josefa, jovem que reconhece as lacunas de seu passado ao ver a imagem de Iñe-e em uma exposição.\r\nCom uma prosa embebida de lirismo, este é um livro sem paralelos na literatura brasileira ao tratar de temas como memória, colonialismo e pertencimento.\r\n\r\n“Um romance que expande as fronteiras da arte literária ao trazer memória, argumentos antropológicos e o melhor que a ficção pode nos oferecer.” ― Itamar Vieira Junior",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "O som do rugido da onça – Vencedor Jabuti 2022"
                        },
                        new
                        {
                            Id = 43,
                            Autor = "James Misse e Pé Da Letra",
                            Capa = "~/img/43/cantigas-de-roda1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "O autor, músico e arte educador james misse, traz neste trabalho um resgate das cantigas de roda como manifestação cultural, desenvolvendo assim a consciência corporal, repertório musical, coordenação motora, socialização e inclusão. Em outras palavras, as cantigas de roda representam uma grande brincadeira com vivencias e descobertas que se transformam em experienciais reais. Esse trabalho conta com as incríveis ilustrações de laura almeida.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Cantigas de Roda"
                        },
                        new
                        {
                            Id = 44,
                            Autor = "Ana Maria Machado",
                            Capa = "~/img/44/mas-que-festa1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Os convites começam a circular: Manuel avisa Frederico, Giovani fala com Beto, Maíra chama Toshiro... De casa em casa, de família em família, a festa de aniversário vai crescendo e ganhando cores, sabores e sotaques.\r\n\r\nNo dia da festa, cada criança chega trazendo um prato preparado em casa e logo a mesa transborda de delícias: cajuzinhos, quibes, pizzas, bolinhos de bacalhau, paellas, pastéis, feijoadas, vatapás, macarronadas e estrogonofes. É fartura garantida!\r\n\r\nNesse clima animado, Ana Maria Machado celebra a diversidade do povo brasileiro. Descendentes de indígenas, africanos, europeus e asiáticos se encontram em uma festa inesquecível, com futebol, música, comilança e muita diversão.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Mas que festa!: Nova edição "
                        },
                        new
                        {
                            Id = 45,
                            Autor = "Tatiana Belinky",
                            Capa = "~/img/45/o-caso-dos-ovos1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "As galinhas estão em greve: não botam mais ovo! Mas a Páscoa vem chegando, e a produção não pode parar...",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "O caso dos ovos"
                        },
                        new
                        {
                            Id = 46,
                            Autor = "Leo Cunha",
                            Capa = "~/img/46/catigamente1.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "Os poemas de Leo Cunha refletem o mundo das crianças e desenvolvem nelas o gosto pela palavra. Os assuntos desses poemas foram retirados do universo infantil, com um olhar sensível e encantador.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Cantigamente"
                        },
                        new
                        {
                            Id = 47,
                            Autor = "Van Macedo",
                            Capa = "~/img/47/versos-magicos1.jpg",
                            ClassificacaoIndicativaId = 4,
                            Descricao = "No livro \"Versos Mágicos: Livro de Poemas\", cada página é uma aventura poética, onde palavras dançam em harmonia com ilustrações vibrantes. Viaje por paisagens poéticas que inspirarão a criatividade dos pequenos leitores, enquanto personagens cativantes ganham vida através das páginas. Com rimas suaves e ilustrações envolventes, este livro é uma janela para a poesia que encanta corações e estimula mentes curiosas. Prepare-se para uma viagem poética cheia de diversão e aprendizado!",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Versos Mágicos"
                        },
                        new
                        {
                            Id = 48,
                            Autor = "José Paulo Paes",
                            Capa = "~/img/48/poemas-para-brincar1.jpg",
                            ClassificacaoIndicativaId = 2,
                            Descricao = "Um clássico da poesia infantil brasileira em que José Paulo Paes propõe a seus leitores brincar com a língua portuguesa. Os poemas apresentam jogos de palavras e até um abecedário com significados inusitados, que diverte, instiga a criatividade das crianças e ainda faz pensar.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Poemas para Brincar"
                        },
                        new
                        {
                            Id = 49,
                            Autor = "Eduardo Rodrigues",
                            Capa = "~/img/49/pequenos-poemas.jpg",
                            ClassificacaoIndicativaId = 3,
                            Descricao = "A natureza, os livros, o tempo, a fome, o medo: tudo é visto com poesia e se transforma em poemas sob o olhar inventivo de Eduardo Rodrigues. Os pequenos poemas, independentes entre si e harmônicos no conjunto que formam, convidam os leitores (não só os pequenos) à graça que as coisas cotidianas têm ou podem ter, se deslocadas da maneira comum como as conhecemos. As ilustrações de Maria Valentina ampliam essa ideia de primeira vez que experimentamos na fruição artística, oferecendo nas poéticas e divertidas criações visuais mais ritmos e melodias para a leitura, a declamação e a escuta dos versos em palavras.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Pequenos Poemas Para Pequenos"
                        },
                        new
                        {
                            Id = 50,
                            Autor = "Roseana Murray e Roger Mello",
                            Capa = "~/img/50/jardins1.jpg",
                            ClassificacaoIndicativaId = 5,
                            Descricao = "“Neste livro repousam a mais linda poesia e os mais lindos jardins, à espera de que o leitor os penetre com a mais singela delicadeza.”\r\nA obra traz quinze pequenos poemas que representam os mais diversos jardins.\r\nCom muita delicadeza, Roseana Murray mexe com o imaginário do leitor. Cada poema-pintura faz os pequenos descobrirem a poesia que vive ao seu redor, nas pequenas coisas, como nas flores, por exemplo.\r\nA organização dos poemas com as ilustrações do talentoso e premiado Roger Mello imprime qualidade que sensibiliza adultos e crianças. É um verdadeiro presente em formato de livro.",
                            Destaque = false,
                            GeneroId = 5,
                            Titulo = "Jardins"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("PerfilRegras", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioRegras", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioPerfil", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsuarioToken", (string)null);
                });

            modelBuilder.Entity("Leiturinha.Models.Avaliacao", b =>
                {
                    b.HasOne("Leiturinha.Models.Livro", "Livro")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Leiturinha.Models.Comentario", b =>
                {
                    b.HasOne("Leiturinha.Models.Livro", "Livro")
                        .WithMany("Comentarios")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Leiturinha.Models.ImagemLivro", b =>
                {
                    b.HasOne("Leiturinha.Models.Livro", "Livro")
                        .WithMany("Imagens")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Leiturinha.Models.Livro", b =>
                {
                    b.HasOne("Leiturinha.Models.ClassificacaoIndicativa", "ClassificacaoIndicativa")
                        .WithMany("Livros")
                        .HasForeignKey("ClassificacaoIndicativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leiturinha.Models.Genero", "Genero")
                        .WithMany("Livros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassificacaoIndicativa");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Leiturinha.Models.ClassificacaoIndicativa", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("Leiturinha.Models.Genero", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("Leiturinha.Models.Livro", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Comentarios");

                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
